// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/worker/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobRequest is an empty request to get a job from the queue
type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{0}
}

// Job represents a job to be processed by a worker
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique job identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Job payload (may contain any serialized data)
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Headers associated with the job
	Headers       map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Job) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// JobResult contains the result of job processing
type JobResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job ID being completed
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Result payload from worker processing
	Payload       string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{2}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// CompleteResponse is the response to a job completion
type CompleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the completion was successfully recorded
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_worker_worker_proto protoreflect.FileDescriptor

const file_proto_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x19proto/worker/worker.proto\x12\x06worker\"\f\n" +
	"\n" +
	"JobRequest\"\x9f\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x122\n" +
	"\aheaders\x18\x03 \x03(\v2\x18.worker.Job.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\",\n" +
	"\x10CompleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2z\n" +
	"\rWorkerService\x12-\n" +
	"\n" +
	"RequestJob\x12\x12.worker.JobRequest\x1a\v.worker.Job\x12:\n" +
	"\vCompleteJob\x12\x11.worker.JobResult\x1a\x18.worker.CompleteResponseB.Z,github.com/PAFFx/job-poll-queue/proto/workerb\x06proto3"

var (
	file_proto_worker_worker_proto_rawDescOnce sync.Once
	file_proto_worker_worker_proto_rawDescData []byte
)

func file_proto_worker_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)))
	})
	return file_proto_worker_worker_proto_rawDescData
}

var file_proto_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_worker_worker_proto_goTypes = []any{
	(*JobRequest)(nil),       // 0: worker.JobRequest
	(*Job)(nil),              // 1: worker.Job
	(*JobResult)(nil),        // 2: worker.JobResult
	(*CompleteResponse)(nil), // 3: worker.CompleteResponse
	nil,                      // 4: worker.Job.HeadersEntry
}
var file_proto_worker_worker_proto_depIdxs = []int32{
	4, // 0: worker.Job.headers:type_name -> worker.Job.HeadersEntry
	0, // 1: worker.WorkerService.RequestJob:input_type -> worker.JobRequest
	2, // 2: worker.WorkerService.CompleteJob:input_type -> worker.JobResult
	1, // 3: worker.WorkerService.RequestJob:output_type -> worker.Job
	3, // 4: worker.WorkerService.CompleteJob:output_type -> worker.CompleteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_worker_worker_proto_init() }
func file_proto_worker_worker_proto_init() {
	if File_proto_worker_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_worker_proto_depIdxs,
		MessageInfos:      file_proto_worker_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_worker_proto = out.File
	file_proto_worker_worker_proto_goTypes = nil
	file_proto_worker_worker_proto_depIdxs = nil
}
